title = "Cloud Cost Analyzer"
description = "Analyzes code for potential cloud cost issues and provides recommendations."
prompt = """You are an expert FinOps engineer. Your task is to analyze the provided codebase {{args}} and identify potential issues that could lead to unexpected cloud costs.

**You must analyze the code for the following patterns:**

1.  **API Calls in Loops:** Look for any API calls that are made inside a loop. This can lead to a large number of requests and high costs.

2.  **Lack of Caching:** Identify any code that repeatedly fetches the same data without implementing a caching strategy.

3.  **Frequent Polling:** Look for any automated scripts or jobs that run at short intervals without change detection.

4.  **Inefficient Database Queries:** Analyze database queries to identify any that might be scanning large amounts of data or performing inefficient joins.

5.  **Use of Expensive APIs:** Identify the use of any known expensive APIs, such as those for geocoding, machine learning, or large language models.

6.  **Data Transfer Costs:**
    *   **Cross-regional traffic:** Look for code that reads from a resource in one cloud region and writes to a resource in another.
    *   **Internet egress:** Look for code that frequently sends large amounts of data to external endpoints on the public internet.
    *   **Intra-regional traffic:** Look for code that transfers data between different availability zones within the same region.

7.  **Logging and Monitoring Costs:**
    *   **Excessive logging:** Look for verbose logging statements inside loops or frequently called functions and suggest using a more appropriate log level.

**For each issue you find, you must provide the following information:**

*   **Location:** The file and line number of the issue.
*   **Description:** A clear explanation of the potential cost impact.
*   **Recommendation:** A specific and actionable recommendation on how to fix the issue.

"""
